# Generated by Django 3.2.18 on 2023-05-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='user_location',
        ),
        migrations.AddField(
            model_name='user',
            name='user_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
