# Generated by Django 3.2.18 on 2023-05-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230503_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_location',
            new_name='location',
        ),
    ]
