# Generated by Django 3.2.18 on 2023-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
