# Generated by Django 3.2.18 on 2023-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='placename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
