# Generated by Django 3.2.18 on 2023-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230502_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='routes',
        ),
        migrations.AddField(
            model_name='article',
            name='routes',
            field=models.TextField(default=''),
        ),
    ]
